"""setup

Revision ID: 315b153775e1
Revises: 5345f4152ec0
Create Date: 2025-07-30 08:58:32.535285

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '315b153775e1'
down_revision = '5345f4152ec0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plants', sa.Column('is_in_stock', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('plants', 'is_in_stock')
    # ### end Alembic commands ###
