"""Initial migration

Revision ID: 5345f4152ec0
Revises: 1fbfa43fdc29
Create Date: 2025-07-30 08:43:55.790194

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5345f4152ec0'
down_revision = '1fbfa43fdc29'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plants', schema=None) as batch_op:
        batch_op.drop_column('is_in_stock')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plants', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_in_stock', sa.BOOLEAN(), nullable=True))

    # ### end Alembic commands ###
